/**
	.rcp/.r36は独自拡張が多く、自分で解析できていない部分あり。なので、defineやenumを使わずに定義する。
*/

struct _RCP_TBL {
	BYTE	note[128]		/* key */
	BYTE	UNKNOWN			/* 0x80 */
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	user_exclusive0	/* 0x90 */
	BYTE	user_exclusive1
	BYTE	user_exclusive2
	BYTE	user_exclusive3
	BYTE	user_exclusive4
	BYTE	user_exclusive5
	BYTE	user_exclusive6
	BYTE	user_exclusive7
	BYTE	ch_exclusive
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN			/* 0xa0 */
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN			/* 0xb0 */
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	machine_DX7_Function	/* 0c0h */
	BYTE	machine_DX_Parameter
	BYTE	machine_DX_RERF
	BYTE	machine_TX_Function
	BYTE	UNKNOWN
	BYTE	machine_FB_01_P_Parameter
	BYTE	machine_FB_01_S_System
	BYTE	machine_TX81Z_V_VCED
	BYTE	machine_TX81Z_A_ACED
	BYTE	machine_TX81Z_P_PCED
	BYTE	machine_TX81Z_S_Sysytem
	BYTE	machine_TX81Z_E_EFFECT
	BYTE	machine_DX7_2_R_REMOTE_SW
	BYTE	machine_DX7_2_A_ACED
	BYTE	machine_DX7_2_P_PCED
	BYTE	machine_TX802_P_PCED
	BYTE	UNKNOWN			/* 0xd0 */
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	machine_mks_7
	BYTE	SET_ROLBASE
	BYTE	SET_ROLPARA
	BYTE	SET_ROLDEV
	BYTE	UNKNOWN			/* 0xe0 */
	BYTE	UNKNOWN
	BYTE	SET_BANK_PRG
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	set_key_scan
	BYTE	SET_MIDI_CH
	BYTE	SET_TEMPO2
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	SET_AFTER_C
	BYTE	SET_MIDI_CONTROL
	BYTE	SET_PROGRAM
	BYTE	SET_AFTER_K
	BYTE	SET_PITCH
	BYTE	UNKNOWN
	BYTE	UNKNOWN			/* 0h0h */
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	set_key_change
	BYTE	COMMENT_START
	BYTE	second_event
	BYTE	SET_MLOOP
	BYTE	SET_MLOOPS
	BYTE	UNKNOWN
	BYTE	UNKNOWN
	BYTE	SET_SAME_MEAS
	BYTE	SET_NOOP
	BYTE	EXIT
	BYTE	UNKNOWN
}
